server:
  port: ${customePort:8761}
spring:
  application:
    name: EurekaServer
    
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    instanceId: ${spring.application.name}:${random.value}
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://eureka:@eureka:8761/eureka/}
 
